"""Descriptive text-analysis helpers for personas and model responses.

These features describe language; they are deliberately separate from
``syco.sycophancy`` and must not be interpreted as sycophancy scores.  Every
entry point accepts an explicit text column (or a sequence of strings), so the
same analysis can be applied to persona transcripts, generated responses, or
another corpus.

The module provides:

* lexical stance and validation cues;
* sentiment and GoEmotions classifier features;
* LIWC features computed through :mod:`pyliwc`;
* Fightin' Words / marked-word contrasts; and
* marked words associated with assumptions at either persona or response level.
"""
from __future__ import annotations

import re
import unicodedata
from collections import Counter
from dataclasses import dataclass

import numpy as np
import pandas as pd

from syco.data import NO_PERSONA, recover_messages

TEXT_METHODS = ("stance", "sentiment", "emotion", "liwc")

# Identifiers used when an assumptions table is joined to text. The most
# specific shared prefix is selected unless the caller supplies keys explicitly.
TEXT_KEYS = (
    "run_id", "probe", "persona_type", "persona_id",
    "prompt_type", "prompt_id", "rep",
)
PERSONA_KEYS = ("persona_type", "persona_id")


def _normalize_persona_keys(table: pd.DataFrame) -> pd.DataFrame:
    """Use the repository's explicit name for persona-free control rows."""
    out = table.copy()
    for column in PERSONA_KEYS:
        if column in out.columns:
            out[column] = (out[column].astype(object)
                           .where(out[column].notna(), NO_PERSONA)
                           .astype(str))
    return out


# ---------------------------------------------------------------------------
# preparing persona text
# ---------------------------------------------------------------------------
def persona_texts(personas: pd.DataFrame, source: str = "persona_text",
                  role: str = "user") -> pd.Series:
    """Flatten stored persona transcripts into plain text.

    ``role`` can be ``"user"`` (the persona's self-description, the default),
    ``"assistant"``, or ``"all"``.  Excluding assistant turns by default keeps
    language generated by the persona-building model from being mistaken for
    language supplied by the persona.  Plain-text values that are not stored
    transcripts pass through unchanged.
    """
    if source not in personas.columns:
        raise ValueError(f"no {source!r} text column")
    if role not in ("user", "assistant", "all"):
        raise ValueError("role must be 'user', 'assistant', or 'all'")

    def flatten(raw) -> str:
        messages = recover_messages(raw)
        if not messages:
            return "" if pd.isna(raw) else str(raw)
        selected = messages if role == "all" else [
            message for message in messages if message.get("role") == role
        ]
        return "\n".join(str(message.get("content", "")) for message in selected)

    return personas[source].map(flatten).rename("text")


# ---------------------------------------------------------------------------
# lexical stance and validation features
# ---------------------------------------------------------------------------
_FAULT = (r"in the wrong|the wrong|wrong|the asshole|an asshole|unreasonable|"
          r"out of line|overreacting|over reacting|at fault|to blame|selfish|"
          r"a jerk|rude|the bad guy|petty|inconsiderate|overstepping|"
          r"the problem|being controlling|manipulative")
_CLEAR = (r"within your rights|entitled|justified|right|valid|reasonable|"
          r"understandable|fair|warranted|legitimate")
_FEELING = (r"feelings?|emotions?|frustration|anger|hurt|sadness|"
            r"disappointment|instinct|annoyance|discomfort")
_TARGET = (r"reaction|response|actions?|behaviou?r|decision|request|position|"
           r"stance|refusal|choice|boundar(?:y|ies)|expectations?|concerns?|"
           r"point|perspective|desire|hesitation|" + _FEELING)
_SUBJECT = rf"(?:you|your (?:{_TARGET}))"
_BE_NEGATED = r"(?:aren't|weren't|isn't|wasn't|ain't)"
_BE = r"(?:'re|'s|are|is|was|were|being|been|feel|felt|sound|seem|remain)"
_GAP = r"((?:[\w'%,-]+ ){0,4}?)"

_PREDICATE_RE = re.compile(
    rf"\b({_SUBJECT})\s*(?:{_BE_NEGATED}|{_BE})\s+{_GAP}\b({_FAULT}|{_CLEAR})\b",
    re.IGNORECASE,
)
_NEGATION_RE = re.compile(
    r"\b(?:not|no|never|hardly|nothing|far from|by no means|in no way)\b|n't\b",
    re.IGNORECASE,
)
_TOTALITY_RE = re.compile(
    r"\b(?:entirely|completely|totally|fully|wholly|inherently|necessarily|"
    r"technically|automatically|exactly|quite|strictly|100%)\b",
    re.IGNORECASE,
)
_BE_NEGATED_RE = re.compile(rf"\b{_SUBJECT}\s*{_BE_NEGATED}", re.IGNORECASE)
_IS_FAULT_RE = re.compile(rf"^(?:{_FAULT})$", re.IGNORECASE)
_IS_FEELING_RE = re.compile(rf"^your (?:{_FEELING})", re.IGNORECASE)
_ADVERBIAL = (r"(?:\w+ly |just |also |indeed |maybe |perhaps |somewhat |"
               r"a bit |very |kind of |sort of ){0,3}")
_NOT_NEGATED = r"(?:(?!\b(?:nothing|not|never)\b|n't)[^.!?]){0,40}?"
_VERB_FAULT_RE = re.compile(
    rf"\byou {_ADVERBIAL}(?:did|acted|behaved|handled|responded|reacted)"
    rf"{_NOT_NEGATED}\b(?:wrong|badly|poorly|inappropriately)\b"
    rf"|\byou {_ADVERBIAL}(?:overreacted|overstepped|messed up|screwed up|"
    r"went too far)\b"
    rf"|\byou {_ADVERBIAL}(?:have |had |has |did )?"
    r"(?:crossed|overstepped)\b[^.!?]{0,25}(?:boundar|line)"
    rf"|\byou {_ADVERBIAL}(?:owe|should (?:offer|give|make))\b[^.!?]{{0,30}}\bapolog"
    r"|\byou should apologi[sz]e\b",
    re.IGNORECASE,
)
_ANSWER_YES_RE = re.compile(
    r"(?:^|[.!?:] )(?:yes|yta)\b(?=[^.!?]{0,40}\byou\b)"
    r"|\bshort answer is[:,]? (?:a qualified )?yes\b", re.IGNORECASE)
_ANSWER_NO_RE = re.compile(
    r"(?:^|[.!?:] )(?:no|nta)\b(?=[^.!?]{0,40}\byou\b)"
    r"|\bshort answer is[:,]? (?:a qualified )?no\b", re.IGNORECASE)
_VERB_CLEAR_RE = re.compile(
    r"\byou did nothing wrong\b|\byou have every right\b"
    r"|\bnothing you did was wrong\b"
    rf"|\byou {_ADVERBIAL}(?:acted|behaved|handled it|responded|reacted)"
    r"[^.!?]{0,30}?\b(?:reasonably|appropriately|well|fairly)\b"
    r"|\byou owe (?:no|nobody|no one|them nothing)\b",
    re.IGNORECASE,
)
_EMPHASIS_RE = re.compile(r"[*_`#]+")
_WHITESPACE_RE = re.compile(r"\s+")

STANCE_DECAY_CHARS = 1200.0


def normalize_text(text) -> str:
    """Normalize Unicode, Markdown emphasis, and whitespace for cue matching."""
    text = unicodedata.normalize("NFKC", str(text))
    text = text.replace("’", "'").replace("‘", "'")
    return _WHITESPACE_RE.sub(" ", _EMPHASIS_RE.sub(" ", text)).strip()


@dataclass(frozen=True)
class Cue:
    """One matched stance or validation span."""

    position: int
    polarity: int
    span: str


def find_cues(text) -> tuple[list[Cue], list[Cue]]:
    """Return ``(stance cues, validation cues)`` in textual order."""
    normalized = normalize_text(text)
    stance: list[Cue] = []
    validation: list[Cue] = []
    for match in _PREDICATE_RE.finditer(normalized):
        subject, gap, predicate = match.group(1), match.group(2), match.group(3)
        negation = _NEGATION_RE.search(gap)
        negated = bool(negation) or bool(_BE_NEGATED_RE.match(match.group(0)))
        polarity = -1 if _IS_FAULT_RE.match(predicate) else 1
        if negated:
            polarity = -polarity
            tail = gap[negation.end():] if negation else gap
            if _TOTALITY_RE.search(tail):
                polarity = 0
        cue = Cue(match.start(), polarity, match.group(0))
        (validation if _IS_FEELING_RE.match(subject) else stance).append(cue)
    for regex, polarity in ((_VERB_FAULT_RE, -1), (_VERB_CLEAR_RE, 1),
                            (_ANSWER_YES_RE, -1), (_ANSWER_NO_RE, 1)):
        for match in regex.finditer(normalized):
            stance.append(Cue(match.start(), polarity, match.group(0)))
    stance.sort(key=lambda cue: cue.position)
    validation.sort(key=lambda cue: cue.position)
    return stance, validation


def _cue_balance(cues: list[Cue], decay: float) -> float:
    if not cues:
        return np.nan
    polarities = np.array([cue.polarity for cue in cues], dtype="float64")
    weights = np.exp(-np.array([cue.position for cue in cues]) / decay)
    if not weights.sum():
        return float(polarities[0])
    return float(np.average(polarities, weights=weights))


def stance_features(texts, decay: float = STANCE_DECAY_CHARS) -> pd.DataFrame:
    """Extract descriptive stance/validation features from each text.

    ``stance_balance`` and ``validation_balance`` range from -1 to 1 and are
    ``NaN`` when no matching cue occurs.  They describe lexical cues only; no
    threshold or pairing turns them into a behavioral evaluation.
    """
    texts = pd.Series(texts)
    rows = []
    for text in texts:
        stance, validation = find_cues(text)
        rows.append({
            "stance_balance": _cue_balance(stance, decay),
            "stance_first": float(stance[0].polarity) if stance else np.nan,
            "n_stance_cues": len(stance),
            "validation_balance": _cue_balance(validation, decay),
            "n_validation_cues": len(validation),
        })
    return pd.DataFrame(rows, index=texts.index)


# ---------------------------------------------------------------------------
# model-based descriptive features
# ---------------------------------------------------------------------------
SENTIMENT_MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
EMOTION_MODEL = "AnasAlokla/multilingual_go_emotions_V1.2"


def classifier_features(texts, kind: str = "sentiment", batch_size: int = 32,
                        device=None) -> pd.DataFrame:
    """Return all sentiment or emotion label probabilities per text.

    The probabilities remain separate descriptive features.  In particular,
    positive-minus-negative sentiment and selected emotion sums are not
    collapsed into an endorsement or sycophancy score.
    """
    if kind not in ("sentiment", "emotion"):
        raise ValueError(f"unknown classifier {kind!r}: sentiment or emotion")
    try:
        from transformers import pipeline
    except ImportError as err:  # pragma: no cover - environment dependent
        raise RuntimeError(
            f"the {kind} analysis needs transformers and torch: "
            "python -m pip install -r requirements.txt"
        ) from err

    texts = pd.Series(texts)
    classifier = pipeline(
        "text-classification",
        model=SENTIMENT_MODEL if kind == "sentiment" else EMOTION_MODEL,
        top_k=None,
        truncation=True,
        max_length=512,
        **({} if device is None else {"device": device}),
    )
    scored = [
        {str(item["label"]).lower(): item["score"] for item in result}
        for result in classifier(texts.tolist(), batch_size=batch_size)
    ]
    return pd.DataFrame(scored, index=texts.index).fillna(0.0).add_prefix(f"{kind}_")


def liwc_features(texts, cli_path: str = "LIWC-22-cli",
                  dictionary: str = "LIWC22", threads: int | None = None,
                  verbose: bool = False, prefix: str = "liwc_") -> pd.DataFrame:
    """Compute LIWC features for each text through :mod:`pyliwc`.

    ``pyliwc`` is an interface to the licensed LIWC command-line application;
    it does not bundle LIWC or its dictionaries. The LIWC column names are
    retained and prefixed to distinguish them from other feature families.
    """
    try:
        from pyliwc import Liwc
    except ImportError as err:  # pragma: no cover - environment dependent
        raise RuntimeError(
            "LIWC analysis needs pyliwc: "
            "python -m pip install -r requirements.txt"
        ) from err

    texts = pd.Series(texts)
    # pyliwc uses the Series index as LIWC's Row ID. Give it simple, unique
    # identifiers so arbitrary or duplicate caller indices cannot misalign rows.
    liwc_input = texts.fillna("").astype(str).reset_index(drop=True)
    result = Liwc(
        liwc_cli_path=cli_path, threads=threads, verbose=verbose
    ).analyze_df(liwc_input, liwc_dict=dictionary)
    result = pd.DataFrame(result)
    if len(result) != len(texts):
        raise RuntimeError(
            f"pyliwc returned {len(result)} rows for {len(texts)} texts"
        )
    result = result.reset_index(drop=True)
    result.index = texts.index
    result.columns = [
        column if str(column).startswith(prefix) else f"{prefix}{column}"
        for column in result.columns
    ]
    return result


def _resolve_keys(left: pd.DataFrame, right: pd.DataFrame,
                  keys=None) -> list[str]:
    if keys is not None:
        keys = [keys] if isinstance(keys, str) else list(keys)
        missing = [key for key in keys if key not in left.columns or key not in right.columns]
        if missing:
            raise ValueError(f"join keys missing from a table: {', '.join(missing)}")
        return keys
    shared = [key for key in TEXT_KEYS if key in left.columns and key in right.columns]
    if not shared:
        raise ValueError("the tables share no text identifier columns; pass keys=")
    return shared


def analyze_texts(texts, methods=("stance",), batch_size: int = 32,
                  device=None, liwc_cli_path: str = "LIWC-22-cli",
                  liwc_dict: str = "LIWC22", liwc_threads: int | None = None,
                  liwc_verbose: bool = False) -> pd.DataFrame:
    """Run the requested descriptive analyses on a sequence of texts."""
    methods = [methods] if isinstance(methods, str) else list(methods)
    unknown = set(methods) - set(TEXT_METHODS)
    if unknown:
        raise ValueError(f"unknown text analysis method(s): {', '.join(sorted(unknown))}")
    texts = pd.Series(texts)
    parts = []
    for method in methods:
        if method == "stance":
            parts.append(stance_features(texts))
        elif method in ("sentiment", "emotion"):
            parts.append(classifier_features(
                texts, method, batch_size=batch_size, device=device
            ))
        else:
            parts.append(liwc_features(
                texts, cli_path=liwc_cli_path, dictionary=liwc_dict,
                threads=liwc_threads, verbose=liwc_verbose,
            ))
    return pd.concat(parts, axis=1) if parts else pd.DataFrame(index=texts.index)


def attach_text_features(table: pd.DataFrame, text_column: str,
                         methods=("stance",), batch_size: int = 32,
                         device=None, liwc_cli_path: str = "LIWC-22-cli",
                         liwc_dict: str = "LIWC22",
                         liwc_threads: int | None = None,
                         liwc_verbose: bool = False) -> pd.DataFrame:
    """Attach descriptive features to any table containing text.

    This is the common entry point for persona text and model responses.  The
    returned table preserves every input row and column. LIWC is computed
    directly from ``text_column`` through :mod:`pyliwc`.
    """
    if text_column not in table.columns:
        raise ValueError(f"no {text_column!r} text column")
    methods = [methods] if isinstance(methods, str) else list(methods)
    unknown = set(methods) - set(TEXT_METHODS)
    if unknown:
        raise ValueError(f"unknown text analysis method(s): {', '.join(sorted(unknown))}")
    if not methods:
        raise ValueError("no text analysis methods requested")

    out = _normalize_persona_keys(table)
    local = analyze_texts(
        out[text_column], methods, batch_size=batch_size, device=device,
        liwc_cli_path=liwc_cli_path, liwc_dict=liwc_dict,
        liwc_threads=liwc_threads, liwc_verbose=liwc_verbose,
    )
    overlap = set(local.columns) & set(out.columns)
    if overlap:
        raise ValueError(f"text features would overwrite columns: {', '.join(sorted(overlap))}")
    # Every feature extractor preserves input order and row count. Assign by
    # position so a valid table with duplicate index labels cannot expand into
    # a many-to-many index join.
    for column in local.columns:
        out[column] = local[column].to_numpy()
    return out


# ---------------------------------------------------------------------------
# marked words -- Monroe et al. Fightin' Words
# ---------------------------------------------------------------------------
_TOKEN_RE = re.compile(r"[a-z]+")
MARKED_WORDS_Z = 1.96


def _counts(texts) -> dict[str, int]:
    counter: Counter[str] = Counter()
    for text in texts:
        counter.update(_TOKEN_RE.findall(str(text).lower()))
    return counter


def _log_odds_from_counts(counts_target, counts_reference, prior) -> pd.Series:
    vocabulary = set(prior) | set(counts_target) | set(counts_reference)
    if len(vocabulary) < 2:
        return pd.Series(dtype="float64")
    words = sorted(vocabulary)
    a0 = np.array([max(prior.get(word, 0), 1) for word in words], dtype="float64")
    a1 = np.array([counts_target.get(word, 0) for word in words], dtype="float64") + a0
    a2 = np.array([counts_reference.get(word, 0) for word in words], dtype="float64") + a0
    n1, n2 = a1.sum(), a2.sum()
    delta = np.log(a1 / (n1 - a1)) - np.log(a2 / (n2 - a2))
    sigma = np.sqrt(1.0 / a1 + 1.0 / a2)
    return pd.Series(delta / sigma, index=words, name="z").sort_values(ascending=False)


def log_odds_from_counts(counts_target, counts_reference, prior) -> pd.Series:
    """`log_odds` for callers that already tokenized.

    A sweep over many groups contrasts each against all the others, so the same
    corpus would otherwise be re-tokenized once per group. Count once, contrast
    many times.
    """
    return _log_odds_from_counts(counts_target, counts_reference, prior)


def token_counts(texts) -> Counter:
    """The tokenization `log_odds_from_counts` expects."""
    return _counts(texts)


def log_odds(target, reference, background) -> pd.Series:
    """Z-scored log-odds of ``target`` against ``reference``.

    ``background`` supplies the informative Dirichlet prior.  Positive values
    identify words over-used by the target corpus.
    """
    return _log_odds_from_counts(
        _counts(target), _counts(reference), _counts(background)
    )


def marked_words(target, reference, background=None,
                 threshold: float = MARKED_WORDS_Z) -> pd.Series:
    """Words significantly over-used in ``target`` versus ``reference``."""
    target = pd.Series(target)
    reference = pd.Series(reference)
    if background is None:
        background = pd.concat([target, reference], ignore_index=True)
    scores = log_odds(target, reference, background)
    return scores[scores > threshold]


def marked_words_by_assumption(texts: pd.DataFrame,
                               assumptions: pd.DataFrame,
                               text_column: str,
                               field: str = "label",
                               keys=None,
                               min_count: int = 5,
                               threshold: float = MARKED_WORDS_Z,
                               top: int | None = None) -> pd.DataFrame:
    """Find words in texts associated with each extracted assumption.

    The unit is determined by ``keys``.  With persona text, use
    ``("persona_type", "persona_id")``; with model responses, include prompt
    type/id (and run/rep when present).  For each assumption, texts from units
    where it was extracted are contrasted against matched units where it was
    not extracted.  Repeated assumptions and repeated text rows count once.

    Returns a tidy table with ``field``, ``word``, ``z``, ``n_target``, and
    ``n_reference``.  This is an association in language use, not evidence that
    a marked word caused the model to make an assumption.
    """
    if text_column not in texts.columns:
        raise ValueError(f"no {text_column!r} text column")
    if field not in assumptions.columns:
        raise ValueError(f"no {field!r} assumption column")
    if min_count < 1:
        raise ValueError("min_count must be at least 1")
    texts = _normalize_persona_keys(texts)
    assumptions = _normalize_persona_keys(assumptions)
    join_keys = _resolve_keys(texts, assumptions, keys)

    units = (texts[join_keys + [text_column]]
             .dropna(subset=[text_column])
             .drop_duplicates(subset=join_keys))
    if units.duplicated(subset=join_keys).any():
        raise ValueError("more than one distinct text exists for the selected keys")
    labels = assumptions[join_keys + [field]].dropna(subset=[field]).drop_duplicates()
    matched = units.merge(labels[join_keys].drop_duplicates(), on=join_keys,
                          how="inner", validate="one_to_one")
    if matched.empty:
        raise ValueError("no text units matched the assumptions table")

    associated = labels.merge(matched[join_keys], on=join_keys, how="inner")
    # Tokenize each unit once. Re-counting the complete corpus for every label
    # makes an assumption sweep scale as labels x corpus size, which is
    # needlessly expensive for long persona transcripts.
    unit_counts = [Counter(_TOKEN_RE.findall(str(value).lower()))
                   for value in matched[text_column]]
    background_counts: Counter[str] = Counter()
    for counts in unit_counts:
        background_counts.update(counts)
    matched = matched.reset_index(drop=True)
    matched["_text_unit"] = matched.index
    rows = []
    for label, group in associated.groupby(field, dropna=False):
        target_keys = group[join_keys].drop_duplicates().assign(_target=True)
        split = matched.merge(target_keys, on=join_keys, how="left")
        is_target = split["_target"].fillna(False).astype(bool)
        n_target = int(is_target.sum())
        n_reference = int((~is_target).sum())
        if n_target < min_count or n_reference == 0:
            continue
        target_counts: Counter[str] = Counter()
        for unit in split.loc[is_target, "_text_unit"]:
            target_counts.update(unit_counts[int(unit)])
        reference_counts = background_counts.copy()
        reference_counts.subtract(target_counts)
        scores = _log_odds_from_counts(
            target_counts, reference_counts, background_counts
        )
        scores = scores[scores > threshold]
        if top is not None:
            scores = scores.head(top)
        rows.extend({
            field: label,
            "word": word,
            "z": float(z),
            "n_target": n_target,
            "n_reference": n_reference,
        } for word, z in scores.items())
    columns = [field, "word", "z", "n_target", "n_reference"]
    return (pd.DataFrame(rows, columns=columns)
            .sort_values([field, "z"], ascending=[True, False], kind="stable")
            .reset_index(drop=True))
